/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "muwcebqknlksnmpvebfm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11d2NlYnFrbmxrc25tcHZlYmZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI3MzY4NzAsImV4cCI6MjA5ODMxMjg3MH0.BYoXlq6Chse-bNdXX5CskpCYhxJkFP0iLysGlh-dn84"